# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

# Fully generated by Qt Designer, nothing has been modified


from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QFrame, QHBoxLayout,
    QLabel, QListWidget, QListWidgetItem, QMainWindow,
    QPushButton, QSizePolicy, QSpacerItem, QVBoxLayout,
    QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1130, 779)
        MainWindow.setMinimumSize(QSize(0, 0))
        MainWindow.setStyleSheet(u"background: #262626;")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.header = QWidget(self.centralwidget)
        self.header.setObjectName(u"header")
        self.header.setMinimumSize(QSize(0, 60))
        self.header.setMaximumSize(QSize(16777215, 54))
        self.header.setStyleSheet(u"")
        self.horizontalLayout_4 = QHBoxLayout(self.header)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_10 = QSpacerItem(4, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_10)

        self.widget_7 = QWidget(self.header)
        self.widget_7.setObjectName(u"widget_7")
        self.widget_7.setMinimumSize(QSize(1090, 0))
        self.widget_7.setMaximumSize(QSize(1090, 16777215))
        self.widget_7.setStyleSheet(u"background: #141414;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;")
        self.horizontalLayout_5 = QHBoxLayout(self.widget_7)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.widget_8 = QWidget(self.widget_7)
        self.widget_8.setObjectName(u"widget_8")
        self.widget_8.setMinimumSize(QSize(130, 0))
        self.horizontalLayout_6 = QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.label_2 = QLabel(self.widget_8)
        self.label_2.setObjectName(u"label_2")
        font = QFont()
        font.setFamilies([u"Titillium Web"])
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color:white;")

        self.horizontalLayout_6.addWidget(self.label_2)


        self.horizontalLayout_5.addWidget(self.widget_8)

        self.horizontalSpacer_11 = QSpacerItem(934, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_5.addItem(self.horizontalSpacer_11)

        self.widget_9 = QWidget(self.widget_7)
        self.widget_9.setObjectName(u"widget_9")
        self.widget_9.setMinimumSize(QSize(0, 0))
        self.horizontalLayout_7 = QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.line_2 = QFrame(self.widget_9)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setMinimumSize(QSize(0, 0))
        self.line_2.setStyleSheet(u"background: #262626;")
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)

        self.horizontalLayout_7.addWidget(self.line_2)

        self.buttonExitMainWindow = QPushButton(self.widget_9)
        self.buttonExitMainWindow.setObjectName(u"buttonExitMainWindow")
        self.buttonExitMainWindow.setMinimumSize(QSize(60, 60))
        self.buttonExitMainWindow.setMaximumSize(QSize(60, 60))
        self.buttonExitMainWindow.setStyleSheet(u"icon:url(:/icons/icons/close.svg);\n"
"border-bottom-right-radius: 20px;")
        self.buttonExitMainWindow.setIconSize(QSize(40, 40))

        self.horizontalLayout_7.addWidget(self.buttonExitMainWindow)


        self.horizontalLayout_5.addWidget(self.widget_9)


        self.horizontalLayout_4.addWidget(self.widget_7)

        self.horizontalSpacer_9 = QSpacerItem(0, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_9)


        self.verticalLayout.addWidget(self.header)

        self.verticalSpacer = QSpacerItem(0, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.mainSection = QWidget(self.centralwidget)
        self.mainSection.setObjectName(u"mainSection")
        self.mainSection.setMinimumSize(QSize(1130, 0))
        self.mainSection.setMaximumSize(QSize(16777215, 16777215))
        self.mainSection.setStyleSheet(u"font-family: 'Titillium Web';\n"
"font-size: 15pt;\n"
"color: white;\n"
"border: none;")
        self.horizontalLayout = QHBoxLayout(self.mainSection)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_3)

        self.section = QWidget(self.mainSection)
        self.section.setObjectName(u"section")
        self.section.setMinimumSize(QSize(300, 0))
        self.section.setMaximumSize(QSize(300, 16777215))
        self.section.setStyleSheet(u"background: #141414;\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;\n"
"")
        self.verticalLayoutForSection = QVBoxLayout(self.section)
        self.verticalLayoutForSection.setSpacing(0)
        self.verticalLayoutForSection.setObjectName(u"verticalLayoutForSection")
        self.verticalLayoutForSection.setContentsMargins(0, 0, 0, 0)
        self.widget_4 = QWidget(self.section)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setMinimumSize(QSize(0, 60))
        self.widget_4.setMaximumSize(QSize(16777215, 60))
        self.widget_4.setStyleSheet(u"font-size: 17pt;")
        self.horizontalLayout_2 = QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_5 = QSpacerItem(20, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_5)

        self.label = QLabel(self.widget_4)
        self.label.setObjectName(u"label")
        self.label.setEnabled(False)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QSize(140, 0))
        self.label.setMaximumSize(QSize(140, 16777215))
        font1 = QFont()
        font1.setFamilies([u"Titillium Web"])
        font1.setPointSize(17)
        self.label.setFont(font1)
        self.label.setStyleSheet(u"color:white;\n"
"border-radius: 0px;")

        self.horizontalLayout_2.addWidget(self.label)

        self.horizontalSpacer_7 = QSpacerItem(20, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_7)

        self.button_macro_folder = QPushButton(self.widget_4)
        self.button_macro_folder.setObjectName(u"button_macro_folder")
        sizePolicy.setHeightForWidth(self.button_macro_folder.sizePolicy().hasHeightForWidth())
        self.button_macro_folder.setSizePolicy(sizePolicy)
        self.button_macro_folder.setMinimumSize(QSize(40, 40))
        self.button_macro_folder.setMaximumSize(QSize(40, 40))
        self.button_macro_folder.setStyleSheet(u"icon: url(:/icons/icons/folder.svg)")
        self.button_macro_folder.setIconSize(QSize(40, 40))

        self.horizontalLayout_2.addWidget(self.button_macro_folder)

        self.horizontalSpacer_8 = QSpacerItem(20, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_8)

        self.button_add_macro = QPushButton(self.widget_4)
        self.button_add_macro.setObjectName(u"button_add_macro")
        sizePolicy.setHeightForWidth(self.button_add_macro.sizePolicy().hasHeightForWidth())
        self.button_add_macro.setSizePolicy(sizePolicy)
        self.button_add_macro.setMinimumSize(QSize(40, 40))
        self.button_add_macro.setMaximumSize(QSize(40, 40))
        self.button_add_macro.setStyleSheet(u"icon:url(:/icons/icons/plus.svg);")
        self.button_add_macro.setIconSize(QSize(40, 40))

        self.horizontalLayout_2.addWidget(self.button_add_macro)

        self.horizontalSpacer_6 = QSpacerItem(20, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_6)


        self.verticalLayoutForSection.addWidget(self.widget_4)

        self.line = QFrame(self.section)
        self.line.setObjectName(u"line")
        self.line.setStyleSheet(u"background: #262626;")
        self.line.setLineWidth(2)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayoutForSection.addWidget(self.line)

        self.widget_5 = QWidget(self.section)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setStyleSheet(u"background: transparent;\n"
"border-radius: 0px;")
        self.verticalLayout_9 = QVBoxLayout(self.widget_5)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.list_macro = QListWidget(self.widget_5)
        self.list_macro.setObjectName(u"list_macro")
        self.list_macro.setStyleSheet(u"QListWidget::item {\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QListWidget::item:active {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: #262626;\n"
"    color: white;\n"
"    border: none;\n"
"	outline: none;\n"
"}\n"
"\n"
"QListWidget::item:focus {\n"
"    outline: none;\n"
"}")
        self.list_macro.setFrameShape(QFrame.Shape.NoFrame)
        self.list_macro.setAutoScrollMargin(0)

        self.verticalLayout_9.addWidget(self.list_macro)


        self.verticalLayoutForSection.addWidget(self.widget_5)


        self.horizontalLayout.addWidget(self.section)

        self.horizontalSpacer = QSpacerItem(20, 0, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.mid = QWidget(self.mainSection)
        self.mid.setObjectName(u"mid")
        self.mid.setMinimumSize(QSize(450, 0))
        self.mid.setMaximumSize(QSize(450, 16777215))
        self.mid.setStyleSheet(u"background: #141414;\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;")
        self.verticalLayoutForSection_2 = QVBoxLayout(self.mid)
        self.verticalLayoutForSection_2.setSpacing(0)
        self.verticalLayoutForSection_2.setObjectName(u"verticalLayoutForSection_2")
        self.verticalLayoutForSection_2.setContentsMargins(0, 0, 0, 0)
        self.header_holder = QWidget(self.mid)
        self.header_holder.setObjectName(u"header_holder")
        self.header_holder.setMinimumSize(QSize(0, 60))
        self.header_holder.setMaximumSize(QSize(16777215, 60))
        self.header_holder.setStyleSheet(u"")
        self.horizontalLayout_11 = QHBoxLayout(self.header_holder)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)

        self.verticalLayoutForSection_2.addWidget(self.header_holder)

        self.line_3 = QFrame(self.mid)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setStyleSheet(u"background: #262626;")
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayoutForSection_2.addWidget(self.line_3)

        self.widget_13 = QWidget(self.mid)
        self.widget_13.setObjectName(u"widget_13")
        self.widget_13.setStyleSheet(u"background: transparent;\n"
"border-radius: 0px;")
        self.verticalLayout_2 = QVBoxLayout(self.widget_13)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.list_event = QListWidget(self.widget_13)
        self.list_event.setObjectName(u"list_event")
        self.list_event.setStyleSheet(u"QListWidget::item {\n"
"    background: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QListWidget::item:active {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: #262626;\n"
"    color: white;\n"
"    border: none;\n"
"	outline: none;\n"
"}\n"
"\n"
"QListWidget::item:focus {\n"
"    outline: none;\n"
"}")
        self.list_event.setFrameShape(QFrame.Shape.NoFrame)
        self.list_event.setAutoScrollMargin(0)
        self.list_event.setDragDropMode(QAbstractItemView.DragDropMode.InternalMove)

        self.verticalLayout_2.addWidget(self.list_event)


        self.verticalLayoutForSection_2.addWidget(self.widget_13)


        self.horizontalLayout.addWidget(self.mid)

        self.horizontalSpacer_2 = QSpacerItem(20, 0, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)

        self.widget_3 = QWidget(self.mainSection)
        self.widget_3.setObjectName(u"widget_3")
        self.verticalLayoutForSection_3 = QVBoxLayout(self.widget_3)
        self.verticalLayoutForSection_3.setSpacing(0)
        self.verticalLayoutForSection_3.setObjectName(u"verticalLayoutForSection_3")
        self.verticalLayoutForSection_3.setContentsMargins(0, 0, 0, 0)
        self.widget_11 = QWidget(self.widget_3)
        self.widget_11.setObjectName(u"widget_11")
        self.widget_11.setMinimumSize(QSize(300, 340))
        self.widget_11.setMaximumSize(QSize(300, 340))
        self.widget_11.setStyleSheet(u"background: #141414;\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;")
        self.verticalLayout_5 = QVBoxLayout(self.widget_11)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.widget_15 = QWidget(self.widget_11)
        self.widget_15.setObjectName(u"widget_15")
        self.widget_15.setMinimumSize(QSize(0, 60))
        self.widget_15.setMaximumSize(QSize(16777215, 60))
        self.horizontalLayout_13 = QHBoxLayout(self.widget_15)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_24 = QSpacerItem(20, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_13.addItem(self.horizontalSpacer_24)

        self.label_7 = QLabel(self.widget_15)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFont(font1)
        self.label_7.setStyleSheet(u"font-size: 17pt;")

        self.horizontalLayout_13.addWidget(self.label_7)

        self.horizontalSpacer_26 = QSpacerItem(230, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_13.addItem(self.horizontalSpacer_26)


        self.verticalLayout_5.addWidget(self.widget_15)

        self.line_4 = QFrame(self.widget_11)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setStyleSheet(u"background: #262626;")
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout_5.addWidget(self.line_4)

        self.widget_16 = QWidget(self.widget_11)
        self.widget_16.setObjectName(u"widget_16")
        self.widget_16.setStyleSheet(u"border-radius: 0px;")
        self.verticalLayout_8 = QVBoxLayout(self.widget_16)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(10, 10, 10, 10)
        self.widget_20 = QWidget(self.widget_16)
        self.widget_20.setObjectName(u"widget_20")
        self.horizontalLayout_14 = QHBoxLayout(self.widget_20)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.button_add_key = QPushButton(self.widget_20)
        self.button_add_key.setObjectName(u"button_add_key")
        self.button_add_key.setEnabled(True)
        self.button_add_key.setMinimumSize(QSize(62, 62))
        self.button_add_key.setMaximumSize(QSize(62, 62))
        font2 = QFont()
        font2.setFamilies([u"Titillium Web"])
        font2.setPointSize(15)
        font2.setKerning(True)
        self.button_add_key.setFont(font2)
        self.button_add_key.setStyleSheet(u"background: #262626;\n"
"")
        self.button_add_key.setAutoDefault(False)

        self.horizontalLayout_14.addWidget(self.button_add_key)

        self.horizontalSpacer_29 = QSpacerItem(10, 20, QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_14.addItem(self.horizontalSpacer_29)

        self.button_add_mouse_button = QPushButton(self.widget_20)
        self.button_add_mouse_button.setObjectName(u"button_add_mouse_button")
        self.button_add_mouse_button.setEnabled(True)
        self.button_add_mouse_button.setMinimumSize(QSize(62, 62))
        self.button_add_mouse_button.setMaximumSize(QSize(62, 62))
        self.button_add_mouse_button.setFont(font2)
        self.button_add_mouse_button.setStyleSheet(u"background: #262626;\n"
"")
        self.button_add_mouse_button.setAutoDefault(False)

        self.horizontalLayout_14.addWidget(self.button_add_mouse_button)

        self.horizontalSpacer_28 = QSpacerItem(10, 20, QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_14.addItem(self.horizontalSpacer_28)

        self.button_add_loop = QPushButton(self.widget_20)
        self.button_add_loop.setObjectName(u"button_add_loop")
        self.button_add_loop.setEnabled(True)
        self.button_add_loop.setMinimumSize(QSize(62, 62))
        self.button_add_loop.setMaximumSize(QSize(62, 62))
        self.button_add_loop.setFont(font2)
        self.button_add_loop.setStyleSheet(u"background: #262626;\n"
"")
        self.button_add_loop.setAutoDefault(False)

        self.horizontalLayout_14.addWidget(self.button_add_loop)

        self.horizontalSpacer_30 = QSpacerItem(10, 20, QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_14.addItem(self.horizontalSpacer_30)

        self.button_add_wait = QPushButton(self.widget_20)
        self.button_add_wait.setObjectName(u"button_add_wait")
        self.button_add_wait.setEnabled(True)
        self.button_add_wait.setMinimumSize(QSize(62, 62))
        self.button_add_wait.setMaximumSize(QSize(62, 62))
        self.button_add_wait.setFont(font2)
        self.button_add_wait.setStyleSheet(u"background: #262626;\n"
"")
        self.button_add_wait.setAutoDefault(False)

        self.horizontalLayout_14.addWidget(self.button_add_wait)


        self.verticalLayout_8.addWidget(self.widget_20)

        self.widget_21 = QWidget(self.widget_16)
        self.widget_21.setObjectName(u"widget_21")
        self.horizontalLayout_15 = QHBoxLayout(self.widget_21)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.button_add_type_text = QPushButton(self.widget_21)
        self.button_add_type_text.setObjectName(u"button_add_type_text")
        self.button_add_type_text.setEnabled(True)
        self.button_add_type_text.setMinimumSize(QSize(62, 62))
        self.button_add_type_text.setMaximumSize(QSize(62, 62))
        self.button_add_type_text.setFont(font2)
        self.button_add_type_text.setStyleSheet(u"background: #262626;\n"
"")
        self.button_add_type_text.setAutoDefault(False)

        self.horizontalLayout_15.addWidget(self.button_add_type_text)

        self.horizontalSpacer_31 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_15.addItem(self.horizontalSpacer_31)


        self.verticalLayout_8.addWidget(self.widget_21)

        self.widget_22 = QWidget(self.widget_16)
        self.widget_22.setObjectName(u"widget_22")
        self.widget_22.setMinimumSize(QSize(0, 80))

        self.verticalLayout_8.addWidget(self.widget_22)


        self.verticalLayout_5.addWidget(self.widget_16)


        self.verticalLayoutForSection_3.addWidget(self.widget_11)

        self.verticalSpacer_2 = QSpacerItem(0, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Maximum)

        self.verticalLayoutForSection_3.addItem(self.verticalSpacer_2)

        self.widget_10 = QWidget(self.widget_3)
        self.widget_10.setObjectName(u"widget_10")
        self.widget_10.setMinimumSize(QSize(300, 0))
        self.widget_10.setMaximumSize(QSize(300, 16777215))
        self.widget_10.setStyleSheet(u"background: #141414;\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;")
        self.verticalLayout_6 = QVBoxLayout(self.widget_10)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.widget_17 = QWidget(self.widget_10)
        self.widget_17.setObjectName(u"widget_17")
        self.widget_17.setMinimumSize(QSize(0, 60))
        self.widget_17.setMaximumSize(QSize(16777215, 60))
        self.horizontalLayout_12 = QHBoxLayout(self.widget_17)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_25 = QSpacerItem(20, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_12.addItem(self.horizontalSpacer_25)

        self.label_8 = QLabel(self.widget_17)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setFont(font1)
        self.label_8.setStyleSheet(u"font-size: 17pt;")

        self.horizontalLayout_12.addWidget(self.label_8)

        self.horizontalSpacer_27 = QSpacerItem(156, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_12.addItem(self.horizontalSpacer_27)


        self.verticalLayout_6.addWidget(self.widget_17)

        self.line_5 = QFrame(self.widget_10)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setStyleSheet(u"background: #262626;")
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout_6.addWidget(self.line_5)

        self.widget_properties = QWidget(self.widget_10)
        self.widget_properties.setObjectName(u"widget_properties")
        self.widget_properties.setStyleSheet(u"border-radius: 0px;\n"
"font-size: 13pt;")

        self.verticalLayout_6.addWidget(self.widget_properties)


        self.verticalLayoutForSection_3.addWidget(self.widget_10)


        self.horizontalLayout.addWidget(self.widget_3)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_4)


        self.verticalLayout.addWidget(self.mainSection)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.button_add_key.setDefault(False)
        self.button_add_mouse_button.setDefault(False)
        self.button_add_loop.setDefault(False)
        self.button_add_wait.setDefault(False)
        self.button_add_type_text.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"LLMacro", None))
        self.buttonExitMainWindow.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Macro", None))
        self.button_macro_folder.setText("")
        self.button_add_macro.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.button_add_key.setText(QCoreApplication.translate("MainWindow", u"Key", None))
        self.button_add_mouse_button.setText(QCoreApplication.translate("MainWindow", u"Mouse \n"
" button", None))
        self.button_add_loop.setText(QCoreApplication.translate("MainWindow", u"Loop", None))
        self.button_add_wait.setText(QCoreApplication.translate("MainWindow", u"Wait", None))
        self.button_add_type_text.setText(QCoreApplication.translate("MainWindow", u"Text", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Properties", None))
    # retranslateUi

